"use client";
import {useEffect,useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {Playoff} from "./playoff";
import type {PlayoffData} from "@/lib/playoff";
type Settings={url:string;visible:boolean;placement:boolean;seeds:string[]};
export function PlayoffSettings({ranking}:{ranking:string[]}){
 const router=useRouter();const [settings,setSettings]=useState<Settings|null>(null),[data,setData]=useState<PlayoffData|null>(null),[seeds,setSeeds]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/admin/playoff",{cache:"no-store"});if(!r.ok)throw new Error("Nie udało się odczytać ustawień play-off.");const value=await r.json() as {settings:Settings;data:PlayoffData};setSettings(value.settings);setSeeds(value.settings.seeds.join("\n"));setData(value.data);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function save(e:FormEvent){e.preventDefault();if(!settings)return;setBusy(true);setMessage("");try{const r=await fetch("/api/admin/playoff",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...settings,seeds:seeds.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)})});const v=await r.json() as {error?:string};if(!r.ok)throw new Error(v.error||"Nie udało się zapisać.");await load();router.refresh();setMessage("Zapisano ustawienia play-off.");}catch(e){setMessage(e instanceof Error?e.message:"Błąd połączenia.");}finally{setBusy(false);}}
 return <><section className="admin-card"><h2>Play-off</h2><p>Wyniki i terminy pobieramy z osobnej zakładki. Nie wpływają na tabelę rundy zasadniczej.</p>{settings&&<form className="admin-form" onSubmit={save}><label>Arkusz play-off<input type="url" required maxLength={1000} value={settings.url} onChange={e=>setSettings({...settings,url:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={settings.visible} onChange={e=>setSettings({...settings,visible:e.target.checked})}/> Pokaż zakładkę Play-off na stronie</label><label className="check-row"><input type="checkbox" checked={settings.placement} onChange={e=>setSettings({...settings,placement:e.target.checked})}/> Włącz mecze o 5. i 7. miejsce</label><label>Końcowe rozstawienie — miejsca 1–8<textarea rows={8} value={seeds} onChange={e=>setSeeds(e.target.value)} placeholder="Jedna drużyna w każdym wierszu, od 1. do 8. miejsca"/></label><p>Zapisz dopiero po zakończeniu rundy zasadniczej. Ta lista nie będzie zmieniać się wraz z tabelą. Użyj dokładnie tych samych nazw drużyn co w arkuszu play-off. Bez listy pary ćwierćfinałowe czytamy w kolejności wierszy: 1–8, 2–7, 3–6, 4–5.</p><button type="button" className="btn secondary" disabled={busy||ranking.length<8} onClick={()=>setSeeds(ranking.slice(0,8).join("\n"))}>Wstaw pierwszą ósemkę z obecnej tabeli</button><p>W blokach „Ćwierćfinał 1/2” i „Półfinał 1/2” wpisuj pierwszy mecz i rewanż. Gospodarze mogą być zamienieni. Wynik złotego seta wpisz przy rewanżu. Pozostałe pary pojawią się po rozstrzygnięciu poprzedniej rundy; terminy i wyniki wpisuj nadal w arkuszu.</p><button className="btn dark" disabled={busy} type="submit">{busy?"Zapisywanie…":"Zapisz play-off"}</button></form>}<p role="status">{message}</p></section>{data&&<section className="admin-card playoff-preview"><h2>Podgląd play-off — także przed publikacją</h2>{data.warnings.map((w,i)=><p role="alert" key={i}>{w}</p>)}<Playoff data={data}/></section>}</>;
}
